/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

const ApiClient = require('./ApiClient')
const Address = require('./apiModels/Address');
const Cart = require('./apiModels/Cart');
const CartItems = require('./apiModels/CartItems');
const Category = require('./apiModels/Category');
const Delivery = require('./apiModels/Delivery');
const ErrorModel = require('./apiModels/ErrorModel');
const ExtendedErrorModel = require('./apiModels/ExtendedErrorModel');
const InlineResponse200 = require('./apiModels/InlineResponse200');
const InlineResponse404 = require('./apiModels/InlineResponse404');
const Method = require('./apiModels/Method');
const Order = require('./apiModels/Order');
const OrderItems = require('./apiModels/OrderItems');
const Payment = require('./apiModels/Payment');
const Product = require('./apiModels/Product');
const Status = require('./apiModels/Status');
const Type = require('./apiModels/Type');
const User = require('./apiModels/User');
const UserAddress = require('./apiModels/UserAddress');
const Vendor = require('./apiModels/Vendor');
const AuthApi = require('./api_classes/AuthApi');
const CartApi = require('./api_classes/CartApi');
const CheckoutApi = require('./api_classes/CheckoutApi');
const OrdersApi = require('./api_classes/OrdersApi');
const ProductsApi = require('./api_classes/ProductsApi');
const StoreApi = require('./api_classes/StoreApi');
const UsersApi = require('./api_classes/UsersApi');
const VendorsApi = require('./api_classes/VendorsApi');

/**
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var profbent = = require('profb_client/index'); // See note below*.
* var xxxSvc = new profbent.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new profbent.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use = require(['profb_client/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new profbent.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new profbent.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module profb_client/index
* @version 1.67
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:profb_client/ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:profb_client/apiModels/Address}
     */
    Address,

    /**
     * The Cart model constructor.
     * @property {module:profb_client/apiModels/Cart}
     */
    Cart,

    /**
     * The CartItems model constructor.
     * @property {module:profb_client/apiModels/CartItems}
     */
    CartItems,

    /**
     * The Category model constructor.
     * @property {module:profb_client/apiModels/Category}
     */
    Category,

    /**
     * The Delivery model constructor.
     * @property {module:profb_client/apiModels/Delivery}
     */
    Delivery,

    /**
     * The ErrorModel model constructor.
     * @property {module:profb_client/apiModels/ErrorModel}
     */
    ErrorModel,

    /**
     * The ExtendedErrorModel model constructor.
     * @property {module:profb_client/apiModels/ExtendedErrorModel}
     */
    ExtendedErrorModel,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:profb_client/apiModels/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse404 model constructor.
     * @property {module:profb_client/apiModels/InlineResponse404}
     */
    InlineResponse404,

    /**
     * The Method model constructor.
     * @property {module:profb_client/apiModels/Method}
     */
    Method,

    /**
     * The Order model constructor.
     * @property {module:profb_client/apiModels/Order}
     */
    Order,

    /**
     * The OrderItems model constructor.
     * @property {module:profb_client/apiModels/OrderItems}
     */
    OrderItems,

    /**
     * The Payment model constructor.
     * @property {module:profb_client/apiModels/Payment}
     */
    Payment,

    /**
     * The Product model constructor.
     * @property {module:profb_client/apiModels/Product}
     */
    Product,

    /**
     * The Status model constructor.
     * @property {module:profb_client/apiModels/Status}
     */
    Status,

    /**
     * The Type model constructor.
     * @property {module:profb_client/apiModels/Type}
     */
    Type,

    /**
     * The User model constructor.
     * @property {module:profb_client/apiModels/User}
     */
    User,

    /**
     * The UserAddress model constructor.
     * @property {module:profb_client/apiModels/UserAddress}
     */
    UserAddress,

    /**
     * The Vendor model constructor.
     * @property {module:profb_client/apiModels/Vendor}
     */
    Vendor,

    /**
    * The AuthApi service constructor.
    * @property {module:profb_client/api_classes/AuthApi}
    */
    AuthApi,

    /**
    * The CartApi service constructor.
    * @property {module:profb_client/api_classes/CartApi}
    */
    CartApi,

    /**
    * The CheckoutApi service constructor.
    * @property {module:profb_client/api_classes/CheckoutApi}
    */
    CheckoutApi,

    /**
    * The OrdersApi service constructor.
    * @property {module:profb_client/api_classes/OrdersApi}
    */
    OrdersApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:profb_client/api_classes/ProductsApi}
    */
    ProductsApi,

    /**
    * The StoreApi service constructor.
    * @property {module:profb_client/api_classes/StoreApi}
    */
    StoreApi,

    /**
    * The UsersApi service constructor.
    * @property {module:profb_client/api_classes/UsersApi}
    */
    UsersApi,

    /**
    * The VendorsApi service constructor.
    * @property {module:profb_client/api_classes/VendorsApi}
    */
    VendorsApi
};
